Demo MVC/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using WebApplication5.Abstract;
using WebApplication5.Concrete;
using WebApplication5.Concrete.Entities;
using WebApplication5.Models;

namespace WebApplication5.Controllers
{
    public class CartController : Controller
    {
        private readonly IMainRepository _mainRepository;
        public CartController(IMainRepository mainRepository)
        {
            _mainRepository = mainRepository;
        }

        // GET: Cart
        public ActionResult Index()
        {
            var cart = GetCart();

            return View(cart);
        }

        [HttpPost] //post method
        public ActionResult AddToCart(AddToCartModel model)
        //public ActionResult AddToCart(int productId, int quantity)
        {
            //check product exsit && amount > quantity
            var product = _mainRepository
                .Products
                .FirstOrDefault(x => x.ProductId == model.ProductId);

            if(product == null)
            {
                //
                return RedirectToAction("Index");
            }
            //get card of user
            var cart = GetCart();
            //add line
            cart.Add(product, model.Quantity);
            //redirect to view cart
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult RemoveFromCart(int productId)
        {
            var product = _mainRepository.Products
                .FirstOrDefault(x => x.ProductId == productId);

            if(product != null)
            {
                var cart = GetCart();
                cart.Remove(product);
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult ClearCart()
        {
            var cart = GetCart();
            cart.Clear();

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult UpdateCart(UpdateCartModel model)
        {
            var product = _mainRepository.Products
                .FirstOrDefault(x => x.ProductId == model.ProductId);

            if(product != null)
            {
                var cart = GetCart();
                cart.Update(product, model.Quantity);
            }

            return RedirectToAction("Index");
        }

        public ActionResult Checkout()
        {
            var cart = GetCart();

            if(cart.LineCollection.Count() == 0)
            {
                return RedirectToAction("Index");
            }

            ViewBag.YourCart = cart;
            ViewBag.PaymentMethods = _mainRepository.PaymentMethods.ToList();

            return View();
        }

        [HttpPost]
        public ActionResult Checkout(CheckoutModel model)
        {
            //kiểm tra giỏ hàng hoặc 1 số ràng buộc mà model không thể check
            var cart = GetCart();
            if(cart.LineCollection.Count() == 0)
            {
                ModelState.AddModelError("", "Giỏ hàng không được để trống");
            }
            //kiểm tra model có hợp lệ hay ko?
            if (ModelState.IsValid)
            {
                //save db
                //customer
                var customer = new Customer()
                {
                    Address = model.ShipTo,
                    Avatar = " ",
                    CustomerName = model.FullName,
                    Email = model.Email,
                    Phone = model.Phone,
                    ProvinceId = 1
                };

                _mainRepository.Add(customer);

                //order
                var order = new Order()
                {
                    CustomerId = customer.CustomerId,
                    OrderDate = DateTime.Now,
                    PaymentMethodId = model.PaymentMethod,
                    ShipTo = model.ShipTo,
                    SubTotal = cart.ComputerTotal()
                };
                _mainRepository.Add(order);

                //order details
                var orderDetails = new List<OrderDetail>();
                foreach(var line in cart.LineCollection)
                {
                    var detail = new OrderDetail()
                    {
                        OrderId = order.OrderId,
                        Quantity = line.Quantity,
                        Price = line.Product.Price,
                        ProductId = line.Product.ProductId
                    };

                    orderDetails.Add(detail);
                }
                _mainRepository.Add(orderDetails);

                //email khách

                string subject = "Thông báo đặt hàng #" + order.OrderId;
                List<string> cc = new List<string>() { "vanvuong.nguyen0408@hotmail.com" };

                StringBuilder sb = new StringBuilder();

                sb.Append($"<h3>Kính chào: {model.FullName}</h3>");
                sb.Append("<p>Đơn hàng của bạn như sau: </p>");

                sb.Append("<table style='border:1px solid #ccc; padding:10px;width:100%'>");
                foreach(var line in cart.LineCollection)
                {
                    sb.Append("<tr>");

                    sb.Append($"<td style='padding:5px'>{line.Product.ProductName}</td>");
                    sb.Append($"<td style='padding:5px'>{line.Product.Price}</td>");
                    sb.Append($"<td style='padding:5px'>{line.Quantity}</td>");
                    sb.Append($"<td style='padding:5px'>{line.Product.Price * line.Quantity}</td>");

                    sb.Append("</tr>");
                }
                sb.Append("</table>");
                sb.Append($"<p>Tổng tiền:<strong>{cart.ComputerTotal()}</strong></p>");
                var pay = _mainRepository.PaymentMethods.FirstOrDefault(x => x.PaymentId == model.PaymentMethod);
                sb.Append($"<p>Hình thức thanh toán: {pay.PaymentName}</p>");
                sb.Append("<p>Nếu có thắc mắc vui lòng liên hệ theo số điện thoại 0914000892</p>");

                var mailSender = new EmailHelper();

                mailSender.Send(model.Email, subject, sb.ToString(), cc);

                //clear
                cart.Clear();
                //lưu thành công thì chuyển về trang thông báo kết quả đặt hàng.
                return RedirectToAction("Completed");
            }
            else
            {
                ModelState.AddModelError("", "Vui lòng nhập đủ dữ liệu.");
            }

            //nếu model lỗi, thì hiển thị lại view Checkout
            return View(model);
        }

        public ViewResult Completed()
        {
            return View();
        }

        //ultilities
        private Cart GetCart()
        {
            var cart = Session["cart"] as Cart;
            if(cart == null)
            {
                cart = new Cart();
                Session["cart"] = cart;
            }
            return cart;
        }
    }
}

Demo MVC/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication5.Abstract;
using WebApplication5.Concrete;
using WebApplication5.Concrete.Entities;
using WebApplication5.Models;

namespace WebApplication5.Controllers
{
    public class ProductsController : Controller
    {
        private readonly IMainRepository _mainRepository;

        public ProductsController(IMainRepository mainRepository)
        {
            _mainRepository = mainRepository;
        }

        // GET: Products
        public ViewResult Index()
        {
            ProductIndexViewModel model = new ProductIndexViewModel();

            //TOP 6
            model.Products = _mainRepository
                .Products
                .OrderByDescending(x => x.ProductId)
                .Take(6)
                .ToList();

            //passing data to view
            return View(model);
        }

        public ViewResult SanPham(
            int page = 1, 
            int pageSize = 6,
            int cat = -1)
        {
            ProductSanPhamViewModel model = new ProductSanPhamViewModel();

            model.Products = _mainRepository
                .Products
                .Where(x => cat == -1 || x.CategoryId == cat)
                .OrderByDescending(x => x.ProductId)
                .Skip((page - 1) * pageSize)
                .Take(pageSize)
                .ToList();

            //paging info

            model.PagingInfo = new PagingInfo()
            {
                CurrentPage = page,
                ItemsPerPage = pageSize
            };

            model.PagingInfo.TotalItems = _mainRepository
                .Products
                .Where(x => cat == -1 || x.CategoryId == cat)
                .Count();

            //get categories
            model.Categories = _mainRepository.Categories.ToList();
            //set current category
            model.CurrentCategory = cat;

            return View(model);
        }

        public ViewResult ChiTiet(int productId)
        {
            ProductChiTietViewModel model = new ProductChiTietViewModel();
            //thong tin product
            model.Product = _mainRepository
                .Products
                .FirstOrDefault(x => x.ProductId == productId);
            //cac san pham lien quan
            model.LinkingProduct = _mainRepository
                .Products
                .Where(x => x.ProductId != productId && x.CategoryId == model.Product.CategoryId)
                .Take(6)
                .ToList();

            //passing data to view
            return View(model);
        }
    }
}

Demo MVC/Views/Products/ChiTiet.cshtml
@model WebApplication5.Models.ProductChiTietViewModel

@{
    ViewBag.Title = "ChiTiet";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<div class="container">
    <div class="row">
        <!--Ảnh sản phẩm-->
        <div class="col-12 col-md-4">
            <img src="@Model.Product.ProductImage"
                 class="img-fluid"/>
        </div>
        <!--Thông tin sản phẩm-->
        <div class="col-12 col-md-8">
            <table class="table table-bordered table-hover">
                <tr>
                    <td>Tên</td>
                    <td>@Model.Product.ProductName</td>
                </tr>
                <tr>
                    <td>Giá</td>
                    <td>@Model.Product.Price</td>
                </tr>
                <tr>
                    <td>Tình trạng</td>
                    <td>
                        @if (Model.Product.Amount > 0)
                        {
                            <span>Còn hàng</span>
                        }
                        else
                        {
                            <span>Hết hàng</span>
                        }
                    </td>
                </tr>
                <tr>
                    <td>Danh mục</td>
                    <td>
                        @Model.Product.CategoryId
                    </td>
                </tr>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <hr />
            <div class="row">
                @foreach (var product in Model.LinkingProduct)
                {
                <div class="col-12 col-md-4 mb-4">
                    @Html.Partial("_ProductSummary", product)
                </div>
                }
            </div>
        </div>
    </div>
</div>

Demo MVC/Views/Products/DanhSach.cshtml
@{
    ViewBag.Title = "DanhSach";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<h2>Product Danh Sach</h2>

Demo MVC/Views/Products/Index.cshtml
@model WebApplication5.Models.ProductIndexViewModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

@if (Model.Products != null && Model.Products.Count() > 0)
{
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
                    <h1 class="display-4">Trang chủ</h1>
                    <p class="lead">Quickly build an effective pricing table for your potential customers with this Bootstrap example. It’s built with default Bootstrap components and utilities with little customization.</p>
                </div>
            </div>
        </div>
        <div class="row">
            @foreach(var product in Model.Products)
            {
            <div class="col-12 col-md-4 mb-4">
                @Html.Partial("_ProductSummary", product)
            </div>
            }
        </div>
    </div>
}
else 
{
    <div>
        Không có sản phẩm nào
    </div>
}

Demo MVC/Views/Products/LienHe.cshtml
@{
    ViewBag.Title = "LienHe";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<h2>Product LienHe</h2>

Demo MVC/Views/Products/SanPham.cshtml
@model WebApplication5.Models.ProductSanPhamViewModel

@{
    ViewBag.Title = "SanPham";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}
<div class="container">
    <div class="row">
        <!--Danh mục sản phẩm-->
        <div class="col-12 col-md-3">
            <div class="list-group">
                @foreach (var category in Model.Categories)
                {
                    <a href="@Url.Action("SanPham","Products",new { cat = category.CategoryId })" class="list-group-item">
                        @category.CategoryName
                    </a>
                }
            </div>
        </div>
        <!--Các sản phẩm-->
        <div class="col-12 col-md-9">
            <div class="row">
                @foreach (var product in Model.Products)
                {
                    <div class="col-12 col-md-4 mb-4">
                        @Html.Partial("_ProductSummary", product)
                    </div>
                }
            </div>
            <div class="row">
                <div class="col-12">
                    <nav aria-label="Page navigation example">
                        <ul class="pagination">
                            @if (Model.PagingInfo.CurrentPage > 1)
                            {
                                <li class="page-item">
                                    <a class="page-link" href="@Url.Action("SanPham","Products",new { page = Model.PagingInfo.CurrentPage - 1, pageSize = Model.PagingInfo.ItemsPerPage, cat = Model.CurrentCategory })" aria-label="Previous">
                                        <span aria-hidden="true">&laquo;</span>
                                    </a>
                                </li>
                            }

                            @for (int i = 1, n = Model.PagingInfo.TotalPages; i <= n; i++)
                            {
                                <li class="page-item @(i == Model.PagingInfo.CurrentPage ? "active" : "")">
                                    <a class="page-link" href="@Url.Action("SanPham","Products",new { page = i, pageSize = Model.PagingInfo.ItemsPerPage , cat = Model.CurrentCategory})">
                                        @i
                                    </a>
                                </li>
                            }

                            @if (Model.PagingInfo.CurrentPage < Model.PagingInfo.TotalPages)
                            {
                                <li class="page-item">
                                    <a class="page-link" href="@Url.Action("SanPham","Products",new { page = Model.PagingInfo.CurrentPage + 1, pageSize = Model.PagingInfo.ItemsPerPage, cat = Model.CurrentCategory })" aria-label="Next">
                                        <span aria-hidden="true">&raquo;</span>
                                    </a>
                                </li>
                            }
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>

Demo MVC/Views/Products/_ProductSummary.cshtml
@model WebApplication5.Concrete.Entities.Product

<div class="card">
    <div class="card-body">
        <div>
            <img src="@Model.ProductImage"
                 class="img-fluid product-image" />
        </div>
        <h3>
            <a href="@Url.Action("ChiTiet","Products",new { productId = Model.ProductId })">
                @Model.ProductName
            </a>
        </h3>
        <div class="d-flex justify-content-between">
            <span>@Model.Price $</span>

            @using (Html.BeginForm("AddToCart", "Cart", FormMethod.Post, new { @class = "frmMain" }))
            {
                @Html.Hidden("ProductId", Model.ProductId)
                @Html.TextBox("Quantity", 1, new { type = "number", min = "1", max = "100" })

                <button type="submit" class="btn btn-primary">
                    Add to cart
                </button>
            }
        </div>
    </div>
</div>